import type { Timestamp } from "firebase/firestore";

export type Product = {
  id: string; // Firestore document ID
  storeId: string;
  name: string;
  sku: string;
  barcode?: string;
  price: number;
  stockQuantity: number;
  category: string;
  imageUrl?: string;
  isVisibleOnPOS: boolean;
  lowStockThreshold?: number;
  description?: string;
  supplier?: string;
  tags?: string[];
  createdAt: Timestamp;
  lastUpdatedAt: Timestamp;
  // For AI features, these might be populated or derived
  salesVelocity?: number; 
  historicalSalesData?: Record<string, number>; 
  supplierLeadTimeDays?: number;
};

export type Customer = {
  id: string; // Firestore document ID
  storeId: string;
  name: string;
  phone?: string;
  email?: string;
  address?: {
    street?: string;
    city?: string;
    state?: string;
    zip?: string;
    country?: string;
  };
  loyaltyPoints: number;
  totalSpent: number; // Consider updating via Cloud Function
  createdAt: Timestamp;
  lastPurchaseAt?: Timestamp;
  notes?: string;
};

export type CartItem = {
  productId: string;
  name: string; // Denormalized
  sku: string; // Denormalized
  quantity: number;
  price: number; // price per unit at the time of adding to cart (unitPrice in Transaction)
  totalPrice: number; // quantity * price
  imageUrl?: string; // Denormalized for cart display
};

export type TransactionItem = {
  productId: string;
  name: string; // Denormalized from product
  sku: string; // Denormalized from product
  quantity: number;
  unitPrice: number; // Price of one unit at the time of sale
  totalPrice: number; // quantity * unitPrice
};

export type Transaction = {
  id: string; // Firestore document ID
  storeId: string;
  transactionDisplayId?: string; // User-friendly ID, potentially generated by Cloud Function
  timestamp: Timestamp;
  cashierId: string; // User UID
  cashierName?: string; // Denormalized
  customerId?: string;
  customerName?: string; // Denormalized
  items: TransactionItem[];
  subtotal: number;
  discountAmount: number;
  taxAmount: number;
  totalAmount: number;
  paymentMethod: 'cash' | 'card' | 'mobile' | 'other' | string;
  paymentStatus: 'completed' | 'pending' | 'refunded' | 'partially_refunded' | 'pending_sync';
  digitalReceiptSent?: boolean;
  receiptChannel?: 'whatsapp' | 'sms' | 'email' | null;
  receiptRecipient?: string | null;
  offlineProcessed?: boolean;
  syncedAt?: Timestamp;
  notes?: string;
  originalTransactionId?: string; // For refunds
  refundReason?: string;
};

export type Store = {
  id: string; // Firestore document ID (matches storeId)
  name: string;
  address?: {
    street?: string;
    city?: string;
    state?: string;
    zip?: string;
    country?: string;
  };
  contactEmail?: string;
  contactPhone?: string;
  taxRate: number; // e.g., 0.08 for 8%
  currency: string; // e.g., "USD"
  ownerId: string; // User UID of the primary admin
  createdAt: Timestamp;
  isActive: boolean;
  subscriptionPlan?: string;
  slogan?: string;
  logoUrl?: string;
  websiteUrl?: string;
  showAddressOnReceipt?: boolean;
  enableOnlineOrderingLink?: boolean;
  // Receipt settings could be a map
  receiptSettings?: {
    headerMessage?: string;
    footerMessage?: string;
    showStoreName?: boolean;
    showStoreAddress?: boolean; // Duplicates main store setting slightly, but specific to receipt
    showStorePhone?: boolean;
    showCashierName?: boolean;
    showTransactionTime?: boolean;
    showLoyaltyPoints?: boolean;
    smsDefaultMessage?: string;
    emailSubject?: string;
    emailBodyPrefix?: string;
  };
};

export type UserDocument = {
  uid: string; // Matches Firebase Auth UID and document ID in 'users' collection
  email: string;
  displayName?: string;
  role: 'admin' | 'manager' | 'cashier';
  storeId: string;
  createdAt: Timestamp;
  lastLoginAt?: Timestamp;
  isActive: boolean;
  avatarUrl?: string; // Optional
};


// For AI Features
export type StockPrediction = {
  productId: string;
  productName: string;
  predictedStockOutDate: string; 
  confidence?: number; 
  reasoning: string;
};

export type ReorderSuggestion = {
  productId: string;
  productName: string;
  suggestedReorderQuantity: number;
  currentStock: number;
  lowStockAlert: boolean;
  reasoning: string;
  nextExpectedOrderDate?: string; 
};

// For Dashboard Page
export type SalesKPIs = {
  totalSales: number;
  totalTransactions: number;
  averageSaleValue: number;
};

export type SalesTrendDataPoint = {
  date: string; 
  sales: number;
};

export type TopSellingProduct = {
  productId: string;
  name: string;
  quantitySold: number;
  totalRevenue: number;
};

export type PaymentMethodDistribution = {
  method: string;
  count: number;
  amount: number;
};
